apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fastapi-chart.fullname" . }}-config
data:
  APP_ENV: {{ .Values.config.APP_ENV | quote }}
  APP_NAME: {{ .Values.config.APP_NAME | quote }}
  APP_VERSION: {{ .Values.config.APP_VERSION | quote }}
